# stock_app/urls.py - 子应用路由文件

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('api/login/', views.login_tushare, name='login'),
    path('api/save_token/', views.save_token, name='save_token'),
    path('api/save_sendkey/', views.save_sendkey, name='save_sendkey'),
    path('api/select/', views.dual_verify_stocks, name='select'),
    path('api/select/start/', views.start_analysis_task, name='select_start'),
    path('api/select/cancel/', views.cancel_analysis_task, name='select_cancel'),
    path('api/select/progress/', views.analysis_task_progress, name='select_progress'),
    path('api/selection/last/', views.selection_last_api, name='selection_last'),
    path('api/portfolio/account/', views.portfolio_account_api, name='portfolio_account'),
    path('api/portfolio/holdings/', views.portfolio_holdings_api, name='portfolio_holdings'),
    path('api/portfolio/holdings/add/', views.portfolio_add_holding_api, name='portfolio_add_holding'),
    path('api/portfolio/holdings/close/', views.portfolio_close_holding_api, name='portfolio_close_holding'),
    path('api/portfolio/holdings/sell/', views.portfolio_sell_holding_api, name='portfolio_sell_holding'),
    path('api/exit-scan/', views.portfolio_exit_scan_api, name='exit_scan'),
    path('api/strategy/run/', views.strategy_lab_run_api, name='strategy_run'),
    path('api/strategy/start/', views.strategy_lab_start_api, name='strategy_start'),
    path('api/strategy/progress/', views.strategy_lab_progress_api, name='strategy_progress'),
    path('api/bull-bear/status/', views.bull_bear_status_api, name='bull_bear_status'),
    path('api/bull-bear/update/', views.bull_bear_update_api, name='bull_bear_update'),
    path('api/bull-bear/chart/<str:filename>/', views.bull_bear_chart_api, name='bull_bear_chart'),
    path('api/fund-flow/status/', views.fund_flow_status_api, name='fund_flow_status'),
    path('api/fund-flow/update/', views.fund_flow_update_api, name='fund_flow_update'),
    path('api/models/retrain/status/', views.model_retrain_status_api, name='model_retrain_status'),
    path('api/models/retrain/run/', views.model_retrain_run_api, name='model_retrain_run'),
    path('api/research/today/', views.research_today_api, name='research_today'),
    path('api/research/reports/', views.research_reports_api, name='research_reports'),
    path('api/research/brief/', views.research_brief_api, name='research_brief'),
    path('api/research/signals/', views.research_signals_api, name='research_signals'),
    path('api/research/preferences/', views.research_preferences_api, name='research_preferences'),
    path('api/research/status/', views.research_status_api, name='research_status'),
    path('api/research/update/', views.research_update_api, name='research_update'),
    path('api/global-radar/status/', views.global_radar_status_api, name='global_radar_status'),
    path('api/global-radar/update/', views.global_radar_update_api, name='global_radar_update'),
    path('api/global-radar/brief/', views.global_radar_brief_api, name='global_radar_brief'),
    path('api/jev/status/', views.jev_status_api, name='jev_status'),
    path('api/jev/predict/', views.jev_predict_api, name='jev_predict'),
    path('api/jev/validate/', views.jev_validate_api, name='jev_validate'),
    path('api/forecast/status/', views.forecast_status_api, name='forecast_status'),
    path('api/forecast/run/', views.forecast_run_api, name='forecast_run'),
    path('api/sector-forecast/status/', views.sector_forecast_status_api, name='sector_forecast_status'),
    path('api/sector-forecast/run/', views.sector_forecast_run_api, name='sector_forecast_run'),
    path('api/status/', views.system_status, name='status'),
    path('api/kline/', views.get_kline_data, name='kline'),
]
