# Generated by Django 5.0.14 on 2026-06-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=64, unique=True),
                ),
                (
                    "total_capital",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=16
                    ),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "portfolio_account",
            },
        ),
        migrations.CreateModel(
            name="PortfolioExitScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("current_data", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_scans",
                        to="stock_app.portfolioaccount",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_exit_scan",
                "ordering": ["-scan_date"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("ts_code", models.CharField(blank=True, default="", max_length=16)),
                ("name", models.CharField(blank=True, default="", max_length=64)),
                ("industry", models.CharField(blank=True, default="", max_length=64)),
                ("shares", models.IntegerField(default=0)),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "cost_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("buy_date", models.CharField(blank=True, default="", max_length=8)),
                (
                    "last_trade_date",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "last_trade_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "peak_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "target_position_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "actual_position_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "position_level",
                    models.CharField(blank=True, default="normal", max_length=32),
                ),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                (
                    "buy_score",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "buy_ai_score",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                ("buy_reason", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("holding", "Holding"), ("closed", "Closed")],
                        default="holding",
                        max_length=16,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="stock_app.portfolioaccount",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_holding",
            },
        ),
        migrations.CreateModel(
            name="PortfolioTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("ADD", "Add"),
                            ("SELL", "Sell"),
                            ("REDUCE", "Reduce"),
                            ("CLOSE", "Close"),
                        ],
                        max_length=12,
                    ),
                ),
                ("trade_date", models.CharField(max_length=8)),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("shares", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "position_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="stock_app.portfolioaccount",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="stock_app.portfolioholding",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_trade",
            },
        ),
        migrations.AddIndex(
            model_name="portfolioholding",
            index=models.Index(
                fields=["account", "code", "status"],
                name="portfolio_h_account_f4db8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliotrade",
            index=models.Index(
                fields=["account", "code", "trade_date"],
                name="portfolio_t_account_8d19f4_idx",
            ),
        ),
    ]
