# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioholding",
            name="exit_rule_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="strategy_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="strategy_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="portfolioholding",
            name="strategy_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
