# Generated by Django 5.0.14 on 2026-08-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_portfolio_strategy_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_date', models.DateField(unique=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('advice', models.TextField(blank=True, default='')),
                ('short_term', models.TextField(blank=True, default='')),
                ('mid_term', models.TextField(blank=True, default='')),
                ('long_term', models.TextField(blank=True, default='')),
                ('industries', models.JSONField(blank=True, default=list)),
                ('stocks', models.JSONField(blank=True, default=list)),
                ('sentiment_stats', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_daily_brief',
                'ordering': ['-brief_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_date', models.DateField(db_index=True)),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_daily_recommendation',
                'ordering': ['recommend_date', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='EarningsForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=16)),
                ('stock_name', models.CharField(blank=True, default='', max_length=64)),
                ('forecast_year', models.IntegerField(blank=True, null=True)),
                ('profit_value', models.FloatField(blank=True, null=True)),
                ('profit_text', models.CharField(blank=True, default='', max_length=128)),
                ('eps_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_earnings_forecast',
            },
        ),
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True)),
                ('stock_code', models.CharField(blank=True, default='', max_length=16)),
                ('stock_name', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_market_event',
            },
        ),
        migrations.CreateModel(
            name='ResearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_stocks', models.JSONField(blank=True, default=list)),
                ('watch_industries', models.JSONField(blank=True, default=list)),
                ('daily_count', models.IntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_preference',
            },
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('stock_code', models.CharField(blank=True, default='', max_length=16)),
                ('stock_name', models.CharField(blank=True, default='', max_length=64)),
                ('industry', models.CharField(blank=True, default='', max_length=64)),
                ('author', models.CharField(blank=True, default='', max_length=128)),
                ('institution', models.CharField(blank=True, default='', max_length=128)),
                ('report_date', models.DateField()),
                ('content_text', models.TextField(blank=True, default='')),
                ('pdf_url', models.CharField(blank=True, default='', max_length=512)),
                ('source_url', models.CharField(max_length=512)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_report',
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('base_url', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_source',
            },
        ),
        migrations.CreateModel(
            name='ResearchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('investment_points', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=16)),
                ('target_stocks', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(blank=True, default='', max_length=32)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('target_price', models.CharField(blank=True, default='', max_length=64)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_summary',
            },
        ),
        migrations.CreateModel(
            name='StockPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField(db_index=True)),
                ('stock_code', models.CharField(max_length=16)),
                ('stock_name', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='daily_brief', max_length=32)),
                ('price_at_pick', models.FloatField(blank=True, null=True)),
                ('ret_t1', models.FloatField(blank=True, null=True)),
                ('ret_t5', models.FloatField(blank=True, null=True)),
                ('ret_t20', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_stock_pick',
            },
        ),
        migrations.AddConstraint(
            model_name='marketevent',
            constraint=models.UniqueConstraint(fields=('event_date', 'stock_code', 'title'), name='uniq_research_event'),
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stock_app.researchreport'),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='stock_app.researchreport'),
        ),
        migrations.AddField(
            model_name='researchreport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stock_app.researchsource'),
        ),
        migrations.AddField(
            model_name='researchsummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='stock_app.researchreport'),
        ),
        migrations.AddConstraint(
            model_name='stockpick',
            constraint=models.UniqueConstraint(fields=('pick_date', 'stock_code', 'source'), name='uniq_research_pick'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['report_date'], name='research_re_report__352fba_idx'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['stock_code'], name='research_re_stock_c_31c1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='researchreport',
            index=models.Index(fields=['industry'], name='research_re_industr_48eb1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchreport',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_research_report_external'),
        ),
    ]
