# Generated by Django 5.0.14 on 2026-08-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_dailybrief_dailyrecommendation_earningsforecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsummary',
            name='investment_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
