# Generated by Django 5.0.14 on 2026-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_alter_researchsummary_investment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpick',
            name='ret_t120',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpick',
            name='ret_t60',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
